spring:
    application:
        name: proxyrasp
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://${DB_HOST:postgresql}:${DB_PORT:5432}/${DB_NAME}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    jpa:
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect