spring:
    application:
        name: proxyrasp
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://postgresql:5432/rasp
        username: root
        password: root
    jpa:
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect